version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fundy-backend
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5680:5672"     # 메시지 송수신 포트
      - "15675:15672"  # 관리 UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
