server:
  port: 8888

spring:
  application:
    name: fundyserver

  config:
    import: classpath:secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  web:
    resources:
      add-mappings: false

