apiVersion: v1
kind: Service
metadata:
  name: fundy-service
spec:
  type: NodePort
  selector:
    app: fundy-server
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888  # 외부에서 접속할 포트
